Socket {
    _connecting: false,
    _hadError: false,
    _handle: TCP {
        _externalStream: {},
        fd: -1,
        reading: true,
        owner: [Circular],
        onread: [Function: onread],
        onconnection: null,
        writeQueueSize: 0
    },
    _parent: null,
    _host: null,
    _readableState: ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null
    },
    readable: true,
    domain: null,
    _events: {
        end: [
            [Object],
            [Function: socketOnEnd]
        ],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        drain: [
            [Function: ondrain],
            [Function: socketOnDrain]
        ],
        timeout: [Function],
        error: [Function: socketOnError],
        close: [
            [Function: serverSocketCloseListener],
            [Function: onServerResponseClose]
        ],
        data: [Function: socketOnData],
        resume: [Function: onSocketResume],
        pause: [Function: onSocketPause]
    },
    _eventsCount: 10,
    _maxListeners: undefined,
    _writableState: WritableState {
        objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: CorkedRequest {
            next: [Object],
            entry: null,
            finish: [F
                unction
            ]
        }
    },
    writable: true,
    allowHalfOpen: true,
    destroyed: false,
    bytesRead: 0,
    _bytesDispatched: 0,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: '',
    server: Server {
        domain: null,
        _events: {
            request: [Function],
            connection: [Function: connectionListener],
            clientError: [Function]
        },
        _eventsCount: 3,
        _maxListeners: undefined,
        _connections: 1,
        _handle: TCP {
            _externalStream: {},
            fd: -1,
            reading: false,
            owner: [Circular],
            onread: null,
            onconnection: [Function: onconnection],
            writeQueueSize: 0
        },
        _usingSlaves: false,
        _slaves: [],
        _unref: false,
        allowHalfOpen: true,
        pauseOnConnect: false,
        httpAllowHalfOpen: false,
        timeout: 120000,
        _pendingResponseData: 0,
        _connectionKey: '6::::8124'
    },
    _server: Server {
        domain: null,
        _events: {
            request: [Function],
            connection: [Function: connectionListener],
            clientError: [Function]
        },
        _eventsCount: 3,
        _maxListeners: undefined,
        _connections: 1,
        _handle: TCP {
            _externalStream: {},
            fd: -1,
            reading: false,
            owner: [Circular],
            onread: null,
            onconnection: [Function: onconnection],
            writeQueueSize: 0
        },
        _usingSlaves: false,
        _slaves: [],
        _unref: false,
        allowHalfOpen: true,
        pauseOnConnect: false,
        httpAllowHalfOpen: false,
        timeout: 120000,
        _pendingResponseData: 0,
        _connectionKey: '6::::8124'
    },
    _idleTimeout: 120000,
    _idleNext: TimersList {
        _idleNext: [Circular],
        _idlePrev: [Circular],
        _timer: Timer { '0': [Function: listOnTimeout], _list: [Circular] },
        _unrefed: true,
        msecs: 120000
    },
    _idlePrev: TimersList {
        _idleNext: [Circular],
        _idlePrev: [Circular],
        _timer: Timer { '0': [Function: listOnTimeout], _list: [Circular] },
        _unrefed: true,
        msecs: 120000
    },
    _idleStart: 1835,
    parser: HTTPParser {
        '0': [Function: parserOnHeaders],
        '1': [Function: parserOnHeadersComplete],
        '2': [Function: parserOnBody],
        '3': [Function: parserOnMessageComplete],
        '4': [Function: onParserExecute],
        _headers: [],
        _url: '',
        _consumed: true,
        socket: [Circular],
        incoming: IncomingMessage {
            _readableState: [Object],
            readable: true,
            domain: null,
            _events: {},
            _eventsCount: 0,
            _maxListeners: undefined,
            socket: [Circular],
            connection: [Circular],
            httpVersionMajor: 1,
            httpVersionMinor: 1,
            httpVersion: '1.1',
            complete: false,
            headers: [Object],
            rawHeaders: [Object],
            trailers: {},
            rawTrailers: [],
            upgrade: false,
            url: '/',
            method: 'GET',
            statusCode: null,
            statusMessage: null,
            client: [Circular],
            _consuming: false,
            _dumped: false
        },
        outgoing: null,
        maxHeaderPairs: 2000,
        onIncoming: [Function: parserOnIncoming]
    },
    on: [Function: socketOnWrap],
    _paused: false,
    read: [Function],
    _consuming: true,
    _httpMessage: ServerResponse {
        domain: null,
        _events: { finish: [Function: resOnFinish] },
        _eventsCount: 1,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _removedHeader: {},
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: false,
        _headerSent: false,
        socket: [Circular],
        connection: [Circular],
        _header: null,
        _headers: null,
        _headerNames: {}
    }
