this.pixiData = {};

(function(){

	pixiData.imgData = ['img/bg0.jpg','img/bg1.jpg','img/bg2.jpg','img/bg3.jpg','img/bg4.jpg','img/bg6.jpg','img/bg5.jpg','img/bg7.jpg','img/bg8.jpg','img/bg9.jpg'];

	pixiData.objData = [
		{
            name:'bg0',
            url:'img/bg0.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:1802*0,
                interactive:true
            }                   
        },
        {
            name:'bg1',
            url:'img/bg1.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:1802*1,
                interactive:true
            }                   
        },
        {
            name:'bg2',
            url:'img/bg2.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:1802*2,
                interactive:true
            }                   
        },
        {
            name:'bg3',
            url:'img/bg3.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:1802*3,
                interactive:true
            }                   
        },
        {
            name:'bg4',
            url:'img/bg4.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:1802*4,
                interactive:true
            }                   
        },
        {
            name:'bg5',
            url:'img/bg5.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:1802*5,
                interactive:true
            }                   
        },
        {
            name:'bg6',
            url:'img/bg6.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:1802*6,
                interactive:true
            }                   
        },
        {
            name:'bg7',
            url:'img/bg7.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:1802*7,
                interactive:true
            }                   
        },
        {
            name:'bg8',
            url:'img/bg8.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:1802*8,
                interactive:true
            }                   
        },
        {
            name:'bg9',
            url:'img/bg9.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:1802*9,
                interactive:true
            }                   
        },
	];

})();