this.pixiData = {};

(function(){

    pixiData.imgData = ['img/bg0.jpg','img/bg1.jpg','img/bg2.jpg','img/bg3.jpg','img/bg4.jpg','img/bg5.jpg','img/bg6.jpg','img/bg7.jpg','img/bg8.jpg','img/bg9.jpg','img/bicycle.png','img/girl.png','img/moon.png','img/phone.png','img/sp.png','img/student.png','img/tips.png','img/woman.png','img/wrod1.png','img/wrod2.png','img/wrod3.png','img/wrod4.png','img/wrod5.png','img/wrod6.png','img/wrod7.png'];

	pixiData.objData = [
		{
            name:'bg0',
            url:'img/bg0.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:722*0
            }                   
        },
        {
            name:'bg1',
            url:'img/bg1.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:722*1
            }                   
        },
        {
            name:'bg2',
            url:'img/bg2.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:722*2-1
            }                   
        },
        {
            name:'bg3',
            url:'img/bg3.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:722*3-1
            }                   
        },
        {
            name:'bg4',
            url:'img/bg4.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:722*4-2
            }                   
        },
        {
            name:'bg5',
            url:'img/bg5.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:722*5-2
            }                   
        },
        {
            name:'bg6',
            url:'img/bg6.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:722*6-3
            }                   
        },
        {
            name:'bg7',
            url:'img/bg7.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:722*7-3
            }                   
        },
        {
            name:'bg8',
            url:'img/bg8.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:722*8-4
            }                   
        },
        {
            name:'bg9',
            url:'img/bg9.jpg',
            type:'Sprite',
            prop:{
                y:0,
                x:722*9-4
            }                   
        },

        {
            name:'bicycle',
            url:'img/bicycle.png',
            type:'Sprite',
            prop:{
                y:135,
                x:722*0+68
            }                   
        },

        {
            name:'wrod1',
            url:'img/wrod1.png',
            type:'Sprite',
            prop:{
                y:90,
                x:722*0+400
            }                   
        },
        {
            name:'wrod2',
            url:'img/wrod2.png',
            type:'Sprite',
            prop:{
                y:390,
                x:722*1+233
            }                   
        },

        {
            name:'wrod3',
            url:'img/wrod3.png',
            type:'Sprite',
            prop:{
                y:220,
                x:722*2+10
            }                   
        },
        {
            name:'student',
            url:'img/student.png',
            type:'Sprite',
            prop:{
                y:180,
                x:722*2+414
            }                   
        },
        {
            name:'wrod4',
            url:'img/wrod4.png',
            type:'Sprite',
            prop:{
                y:502,
                x:722*3+513
            }                   
        },
        {
            name:'woman',
            url:'img/woman.png',
            type:'Sprite',
            prop:{
                y:166,
                x:722*4+450
            }                   
        },
        {
            name:'phone',
            url:'img/phone.png',
            type:'Sprite',
            prop:{
                y:366,
                x:722*5+311
            }                   
        },
        {
            name:'moon',
            url:'img/moon.png',
            type:'Sprite',
            prop:{
                y:41,
                x:722*6+136
            }                   
        },
        {
            name:'girl',
            url:'img/girl.png',
            type:'Sprite',
            prop:{
                y:252,
                x:722*8+7
            }                   
        },
        {
            name:'wrod6',
            url:'img/wrod6.png',
            type:'Sprite',
            prop:{
                y:114,
                x:722*8+367
            }                   
        },
        {
            name:'wrod7',
            url:'img/wrod7.png',
            type:'Sprite',
            prop:{

                y:475,
                x:722*8+690
                
            }                   
        },


        {
            name:'sp',
            url:'img/sp.png',
            type:'Sprite',
            prop:{

                y:10,
                x:722*9+120

            }                   
        },

	];

})();